"""Generate a Keep a Changelog section from Conventional Commits.

Usage:
    python scripts/generate_changelog.py [--version 0.2.0] [--since <ref>] [--to <ref>] [--prepend]

Without ``--version`` an ``[Unreleased]`` section is printed; with it a dated
release section. The range defaults to the latest tag up to HEAD, or the
whole history without a tag. ``--prepend`` inserts the section at the top of
CHANGELOG.md, creating the file when needed.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = REPO_ROOT / "CHANGELOG.md"

_HEADER_RE = re.compile(
    r"^(?P<type>[a-z]+)(?:\((?P<scope>[\w.-]+)\))?(?P<breaking>!)?: (?P<desc>.+)$",
    re.IGNORECASE,
)

# Conventional Commit type -> Keep a Changelog group
_GROUP_BY_TYPE = {
    "feat": "Added",
    "fix": "Fixed",
    "perf": "Changed",
    "refactor": "Changed",
    "docs": "Changed",
    "style": "Changed",
    "build": "Changed",
    "deprecate": "Deprecated",
    "remove": "Removed",
    "security": "Security",
}
# Too noisy for the changelog.
_NOISE = {"chore", "ci", "test", "revert"}

# The header of a freshly created changelog; an existing file keeps its own.
_CHANGELOG_HEADER = (
    "# Changelog\n\n"
    "This project follows [Semantic Versioning](https://semver.org/).\n"
    "Entries are generated by `scripts/generate_changelog.py`.\n\n"
)


def _stdout() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass


def git_log(since: str | None, to: str) -> list[tuple[str, str, str]]:
    """``(hash, subject, body)`` per commit, newest first."""
    fmt = "%H%x1f%s%x1f%b%x1e"
    args = (
        ["git", "log", "--no-merges", f"--format={fmt}", to]
        if since is None
        else ["git", "log", "--no-merges", f"--format={fmt}", f"{since}..{to}"]
    )
    out = subprocess.run(
        args,
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    ).stdout
    commits: list[tuple[str, str, str]] = []
    for rec in out.split("\x1e"):
        rec = rec.strip("\n")
        if not rec:
            continue
        parts = rec.split("\x1f")
        subject = parts[1] if len(parts) > 1 else ""
        body = parts[2] if len(parts) > 2 else ""
        commits.append((parts[0], subject, body))
    return commits


def latest_tag() -> str | None:
    out = subprocess.run(
        ["git", "describe", "--tags", "--abbrev=0"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return out.stdout.strip() if out.returncode == 0 else None


def group_commits(commits: list[tuple[str, str, str]]) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {
        "Added": [],
        "Fixed": [],
        "Changed": [],
        "Deprecated": [],
        "Removed": [],
        "Security": [],
        "Breaking Changes": [],
    }
    for _, subject, body in commits:
        m = _HEADER_RE.match(subject)
        if not m:
            continue
        ctype = m.group("type").lower()
        if ctype in _NOISE:
            continue
        scope = m.group("scope")
        desc = m.group("desc")
        breaking = bool(m.group("breaking")) or "BREAKING CHANGE:" in body.upper()
        entry = f"- **{scope}**: {desc}" if scope else f"- {desc}"
        if breaking:
            if entry not in groups["Breaking Changes"]:
                groups["Breaking Changes"].append(entry)
        else:
            group = _GROUP_BY_TYPE.get(ctype)
            if group and entry not in groups[group]:
                groups[group].append(entry)
    return {k: v for k, v in groups.items() if v}


def render(title: str, groups: dict[str, list[str]]) -> str:
    lines = [f"## {title}", ""]
    for name, entries in groups.items():
        lines.append(f"### {name}")
        lines.append("")
        lines.extend(entries)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_section(
    version: str | None, since: str | None = None, to: str = "HEAD"
) -> str:
    """The full section; ``version=None`` renders Unreleased."""
    if since is None:
        since = latest_tag()
    groups = group_commits(git_log(since, to))
    if version:
        title = f"[{version}] - {datetime.now(timezone.utc).date().isoformat()}"
    else:
        title = "[Unreleased]"
    return render(title, groups)


def prepend(section: str) -> None:
    """Insert the section at the top of CHANGELOG.md, keeping the file header.

    An existing ``[Unreleased]`` section is replaced, because the new section
    covers the same commits; every dated release section below it is kept.
    """
    if CHANGELOG.exists():
        original = CHANGELOG.read_text(encoding="utf-8")
        headings = list(re.finditer(r"^## .*$", original, re.MULTILINE))
        if headings:
            head = original[: headings[0].start()]
            first = headings[0]
            # The new section always supersedes an Unreleased one: a release
            # section covers those commits, and a regenerated Unreleased
            # section replaces the stale draft.
            if "[Unreleased]" in first.group():
                rest_start = headings[1].start() if len(headings) > 1 else len(original)
            else:
                rest_start = first.start()
            rest = original[rest_start:]
        else:
            head = original.rstrip() + "\n\n"
            rest = ""
    else:
        head = _CHANGELOG_HEADER
        rest = ""
    body = section if not rest else section.rstrip("\n") + "\n\n" + rest.lstrip("\n")
    CHANGELOG.write_text(head + body, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a CHANGELOG section from git commits"
    )
    parser.add_argument(
        "--version", help="version to render (0.2.0); Unreleased when omitted"
    )
    parser.add_argument(
        "--since", help="start ref (tag or commit); the latest tag when omitted"
    )
    parser.add_argument("--to", default="HEAD", help="end ref, HEAD by default")
    parser.add_argument(
        "--prepend", action="store_true", help="prepend the section to CHANGELOG.md"
    )
    args = parser.parse_args(argv)

    section = build_section(args.version, args.since, args.to)
    if args.prepend:
        prepend(section)
        print(f"written to {CHANGELOG}")
    else:
        sys.stdout.write(section)
    return 0


if __name__ == "__main__":
    _stdout()
    raise SystemExit(main())
